#
# QtSOAP
#

SET(QtSOAP_DIR "$ENV{MAF3_FOUNDATION_LIB_DIR}/qtsoap/")
INCLUDE_DIRECTORIES("${QtSOAP_DIR}/include/")
LINK_DIRECTORIES(${LINK_DIRECTORIES} "${QtSOAP_DIR}/lib/")
#debug or release
SET(QTSOAP_LIBRARY "QtSolutions_SOAP-2.7")
SET(QtSOAP_FOUND TRUE)    

