#
# QXMLRPC
#

SET(QXMLRPC_DIR "$ENV{MAF3_FOUNDATION_LIB_DIR}/qxmlrpc/")
INCLUDE_DIRECTORIES("${QXMLRPC_DIR}/include/")
LINK_DIRECTORIES(${LINK_DIRECTORIES} "${QXMLRPC_DIR}/lib/")
#debug or release
SET(QXMLRPC_LIBRARY "qxmlrpc")
SET(QXMLRPC_FOUND TRUE)    

